/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

        assertEquals(3,classUnderTest.roll(3).length);

        assertTrue(classUnderTest.containsDuplicates(new int[]{2,2,3,4}));

        assertEquals(2.5,classUnderTest.average(new int[]{2,2,2,4}));

        assertArrayEquals(new int[]{2,2,2,2},classUnderTest.lowestAvg(new int[][]{{2,2,2,2},{3,3,3,3}}));

        assertEquals("High: 72\n" +
                "Low : 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69", classUnderTest.maxAndMin(new int[][] {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
        }));

        List<String> list = new LinkedList<>();
        list.add("Naeem");
        list.add("Alomari");
        list.add("Alomari");

        assertEquals("Alomari",classUnderTest.tally(list));
    }
}
