/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restaurant;


public class Main {
    public static void main(String[] args) {
        System.out.println("PAASSS NNN");

    Restaurant macDolads =new Restaurant("macDolads" ,6, 20);
    System.out.println(macDolads);

    Restaurant KFC =new Restaurant("KFC" , 2,10);
        System.out.println(KFC);

        Restaurant ابوعقله_للفلافل = new Restaurant("ابوعقله_للفلافل" , 0, 100);
        System.out.println(ابوعقله_للفلافل);

        Restaurant review =new Review("jcjhv", 2,5, "kjbvkjlkjnv", "ajbce", 3);
        System.out.println(review);
    }

}
