/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restaurant;

import org.junit.jupiter.api.Test;

class MainTest {

    @Test
    public void someLibraryMethodReturnTrue() {
        Main classUnderTest = new Main();
    }


    @Test
    public void constructorRestaurant() {
        Restaurant test = new Restaurant("kfc", 4, 10);
    }
}
