/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package restaurant;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test void someLibraryMethodReturnsTrue() {
        Main classUnderTest = new Main();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
