/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        String actual = App.readFile("C:\\Users\\Student\\401Java\\java-fundemantals\\linter\\app\\src\\main\\resources\\gates.js");
        assertTrue(!actual.contains(classUnderTest.readFile("Line " + 3 + ": Missing Semicolon."+"\n")));

    }
}
