/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
//        Path place = Paths.get("src\\main\\resources\\gates.js");
        String answer="function and(a,b) {  if (a === 1 && b === 1) {Line 3: Missing Semicolon.  } " +
                "else {Line 5: Missing Semicolon.  }}function or(a,b) {  if (a === 1)Line 11: " +
                "Missing Semicolon.  if (b === 1)Line 13: Missing Semicolon.  elseLine 15: Missing " +
                "Semicolon.}function xor(a,b) {  if (and(a,b))    return 0;  return or(a,b);}function " +
                "not(a) {  if (a === 0)Line 26: Missing Semicolon.  elseLine 28: Missing Semicolon.}function " +
                "nand(a,b) {Line 32: Missing Semicolon.}function nor(a,b) " +
                "{Line 36: Missing Semicolon.}function add1(a,b) {Line 40: Missing Semicolon." +
                "Line 41: Missing Semicolon.  return {sum, overflow}}function zadd1(a,b,z) {  var ones, zf;  zf = or(or(and(a,b), and(b,z)), and(a,z));  j = or(a, nor(b,z));Line 50: Missing Semicolon.Line 51: Missing Semicolon.  console.log(\"jkl\", j, k, l);  ones = xor(j, xor(k, l));  return {ones, zf};}Line 59: Missing Semicolon.Line 60: Missing Semicolon.Line 61: Missing Semicolon.Line 62: Missing Semicolon.function add2(a,b) {Line 64: Missing Semicolon.  ones = add1(a[1], b[1]);}Line 70: Missing Semicolon.Line 71: Missing Semicolon.Line 72: Missing Semicolon.Line 73: Missing Semicolon.Line 74: Missing Semicolon.Line 76: Missing Semicolon.Line 77: Missing Semicolon.Line 78: Missing Semicolon.Line 79: Missing Semicolon.Line 80: Missing Semicolon.Line 82: Missing Semicolon.Line 83: Missing Semicolon.Line 84: Missing Semicolon.Line 85: Missing Semicolon.Line 86: Missing Semicolon.Line 88: Missing Semicolon.Line 89: Missing Semicolon.Line 90: Missing Semicolon.Line 91: Missing Semicolon.Line 92: Missing Semicolon.Line 94: Missing Semicolon.Line 95: Missing Semicolon.Line 96: Missing Semicolon.Line 97: Missing Semicolon.Line 98: Missing Semicolon.Line 99: Missing Semicolon.Line 100: Missing Semicolon.Line 101: Missing Semicolon.";
        assertEquals(answer,App.readFile("src\\main\\resources\\gates.js"));

    }
}
